### ISSUE TITLE
安装崩溃

### ISSUE THREAD

**Issue by easyandroid** [flyou/Girls#1]
E/AndroidRuntime(27446): java.lang.RuntimeException: Unable to instantiate appli
cation com.android.tools.fd.runtime.BootstrapApplication: java.lang.ClassNotFoun
dException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication
" on path: DexPathList[[zip file "/data/app/com.flyou.girls-1.apk"],nativeLibrar
yDirectories=[/data/app-lib/com.flyou.girls-1, /vendor/lib, /system/lib]]
E/AndroidRuntime(27446):        at android.app.LoadedApk.makeApplication(LoadedA
pk.java:512)
E/AndroidRuntime(27446):        at android.app.ActivityThread.handleBindApplicat
ion(ActivityThread.java:4620)
E/AndroidRuntime(27446):        at android.app.ActivityThread.access$1300(Activi
tyThread.java:168)
E/AndroidRuntime(27446):        at android.app.ActivityThread$H.handleMessage(Ac
tivityThread.java:1436)
E/AndroidRuntime(27446):        at android.os.Handler.dispatchMessage(Handler.ja
va:107)
E/AndroidRuntime(27446):        at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(27446):        at android.app.ActivityThread.main(ActivityThrea
d.java:5398)
E/AndroidRuntime(27446):        at java.lang.reflect.Method.invokeNative(Native
Method)
E/AndroidRuntime(27446):        at java.lang.reflect.Method.invoke(Method.java:5
25)
E/AndroidRuntime(27446):        at com.android.internal.os.ZygoteInit$MethodAndA
rgsCaller.run(ZygoteInit.java:836)
E/AndroidRuntime(27446):        at com.android.internal.os.ZygoteInit.main(Zygot
eInit.java:603)
E/AndroidRuntime(27446):        at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime(27446): Caused by: java.lang.ClassNotFoundException: Didn't fin
d class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList
[[zip file "/data/app/com.flyou.girls-1.apk"],nativeLibraryDirectories=[/data/ap

**Comment by shixinzhang** [comment]
奔溃+1， 博主解决了有空回复一下

**Comment by luffykou** [comment]
本地Android Studio环境问题，[http://stackoverflow.com/questions/33967703/unable-to-instantiate-application-com-android-tools-fd-runtime-bootstrapapplicat](解决方案：http://stackoverflow.com/questions/33967703/unable-to-instantiate-application-com-android-tools-fd-runtime-bootstrapapplicat)

话说不能自己查一下么，同学

**Comment by luffykou** [comment]
本地Android Studio环境问题，http://stackoverflow.com/questions/33967703/unable-to-instantiate-application-com-android-tools-fd-runtime-bootstrapapplicat

话说不能自己查一下么，同学

**Comment by shixinzhang** [comment]
@luffykou 我不明白的是我直接安装他的debug包，难道还需要修改自己的AS配置吗

**Comment by luffykou** [comment]
我试过直接安装[girls.apk](http://7xl7dy.com1.z0.glb.clouddn.com/app-debug.apk)
- 努比亚 Andorid5.0系统——安装正常，首页可用，其他问题不表。
- Nexus 6P Android6.0系统——安装正常，可用。

所以，请把问题描述清楚：
- 什么环境（开发环境、运行环境）下
- 做什么操作
- 发生了什么问题

**Comment by shixinzhang** [comment]
Nexus 5 Android 4.4.4 启动奔溃

**Comment by flyou** [comment]
不好意思是我传的包有问题，大家在自己的环境下 编译下就ok了

**Comment by luffykou** [comment]
@shixinzhang 
android4.4.4模拟器试了下，确实启动崩溃。

打了新包 [下载Girls-V1.02.apk](http://7xqi9h.com1.z0.glb.clouddn.com/Girls-V1.02.apk)

**Comment by flyou** [comment]
@luffykou 
我这边用的4.4的测试机没有问题
5.0也没有问题啊
方便的话你可以提供日志

**Comment by luffykou** [comment]
android 4.4.4模拟器，使用你在README.md提供的apk
- install信息
  1877 KB/s (2409087 bytes in 1.252s)
  WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
  pkg: /data/local/tmp/girls_app-debug.apk
  Success
- 启动信息
  04-23 00:04:56.793 1868-1868/com.flyou.girls D/dalvikvm: Not late-enabling CheckJNI (already on)
  04-23 00:04:56.833 1868-1868/com.flyou.girls D/AndroidRuntime: Shutting down VM
  04-23 00:04:56.833 1868-1868/com.flyou.girls W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xb3cbbb20)
  04-23 00:04:56.833 1868-1868/com.flyou.girls E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.flyou.girls, PID: 1868
                                                             java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.flyou.girls-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flyou.girls-1, /system/lib]]
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.flyou.girls-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flyou.girls-1, /system/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by flyou** [comment]
@我传的包有问题，已经更换

**Comment by flyou** [comment]
@luffykou 我传的包有问题，我的锅，已经更换
